linters:
  enable-all: true
  disable:
  - forbidigo
  - godox
  - wsl
  - gci
  - exhaustivestruct
  - goerr113
  - gofumpt
  # Deprecated
  - maligned
  - scopelint
  - interfacer
  - golint

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
