version: "2"
linters:
  default: all
  disable:
    - cyclop
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - gomoddirectives
    - inamedparam
    - ireturn
    - mnd
    - nestif
    - nonamedreturns
    - testpackage
    - varnamelen
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: gopkg.in/yaml.v2
              desc: use yaml.v3 only
    revive:
      rules:
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
        - name: unused-receiver
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
